DROP TABLE IF EXISTS TBL_EMPLOYEES;
DROP TABLE IF EXISTS TBL_DISH;
DROP TABLE IF EXISTS TBL_ORDERS;

CREATE TABLE TBL_EMPLOYEES (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  job VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL
);
CREATE TABLE TBL_DISH (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  dish_name VARCHAR(250) NOT NULL,
  price DOUBLE NOT NULL
);
CREATE TABLE TBL_ORDERS (
id INT AUTO_INCREMENT PRIMARY KEY,
order_name INT NOT NULL,
client_name VARCHAR (250) NOT NULL,
phone_number INT DEFAULT NULL,
full_price DOUBLE NOT NULL
);